name: Feature Request
description: Request a feature
body:
  - type: markdown
    attributes:
      value: |
        # Octopus Copilot: Feature Request
        Thanks for taking the time to suggest a feature!
        
        While the solutions engineering team will make a reasonable effort to respond to this request, the Octopus Copilot has no Support Level Agreement (SLA).

  - type: textarea
    id: prompt
    attributes:
      label: Chat query
      description: What prompt would you like to see added?
      placeholder: Chat prompt
    validations:
      required: true

  - type: textarea
    id: action
    attributes:
      label: Action
      description: What should this prompt do?
      placeholder: Prompt action
    validations:
      required: true

